# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 #  Runs a single command using the runners shell
#       - name: Clean up
#         run: git remote prune origin
   
#       - name: Set main branch
#         run: git config --global init.defaultBranch main
        
#       - name: Clone a template repo
#         run: gh repo create test2 -p git@github.com:neurogamer/template.git --public --clone
#         env:
#           GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }}
    
          
#       - name: Get organization ID
#         run: |
#           ID_ORG=`curl -s -u remus@ilies.co.uk:${{ secrets.REMUS_TOKEN }} "https://api.github.com/orgs/neurogamer-team" | jq ."id"` 
     
#       - name:  echo Org ID
#         run: |
#           echo $ID_ORG
#         env:
#           GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }} 
   
          
#       - name: Get team ID
#         run: |
#           ID_TEAM=`curl -s -u remus@ilies.co.uk:${{ secrets.REMUS_TOKEN }} "https://api.github.com/orgs/neurogamer-team/teams" | jq --arg team "cool-gen-devs" | jq .[] | jq ."id"` \
#         env:
#           GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }}  
#       - name: echo team ID   
#         run: |
#           echo $ID_TEAM
#         env:
#           GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }} 
           
      - name: Run a multi-line script
        run: |
         curl -u remus@ilies.co.uk:${{ secrets.REMUS_TOKEN }} -X PUT -H "Accept: application/vnd.github.v3+json" https://api.github.com/organizations/99800456/team/5687593/repos/neurogamer-team/test2 -d '{"permission":"pull"}'
        env:
          GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }} 
   
