# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
   # Runs a single command using the runners shell
      - name: Clean up
        run: git remote prune origin --dry-run
   
      - name: Set main branch
        run: git config --global init.defaultBranch main
        
      - name: Clone a template repo
        run: gh repo create git@github.com:neurogamer/test-project -p git@github.com:neurogamer/template.git -t neurogmaer-team/cool-gen-devs --public --clone
        env:
          GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }}
      
      
      - name: Add a team to repo
        run: gh repo neurogamer/test-project -t cool-gen-devs
        env:
          GITHUB_TOKEN: ${{ secrets.REMUS_TOKEN }}
#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
